---
# prometheus_server/tasks/main.yml

- name: 'Fail if prerequisites for TLS are missing: tls_certificate_crt_path'
  ansible.builtin.fail:
    msg: 'Variable tls_certificate_crt_path is not set'
  when:
    - 'enable_tls | bool'
    - 'tls_certificate_crt_path is undefined'

- name: 'Fail if prerequisites for TLS are missing: tls_certificate_key_path'
  ansible.builtin.fail:
    msg: 'Variable tls_certificate_key_path is not set'
  when:
    - 'enable_tls | bool'
    - 'tls_certificate_key_path is undefined'

- name: 'Populate the package name variable depending on the OS'
  ansible.builtin.include_tasks: package_name.yml

- name: 'Populate the service name variable depending on the OS'
  ansible.builtin.include_tasks: service_name.yml

- name: 'Install the package'
  ansible.builtin.package:
    name: "{{ prometheus_server_package_name }}"
    state: 'present'

- name: 'Create the configuration file'
  ansible.builtin.template:
    src: 'prometheus.yml.j2'
    dest: '/etc/prometheus/prometheus.yml'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Restart the prometheus service'

- name: 'Create rules.yml'
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/prometheus/{{ item }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: "{{ alert_rules_files }}"
  when:
    - 'alert_rules_files is defined'
    - 'copy_alert_rules_files | bool'
  notify:
    - 'Restart the prometheus service'

- name: 'Adapt the sysconfig file for TLS'
  ansible.builtin.template:
    src: 'etc_sysconfig_prometheus.j2'
    dest: '/etc/sysconfig/prometheus'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when:
    - 'ansible_os_family == "Suse" or ansible_os_family == "openSUSE MicroOS"'
    - 'enable_tls | bool'
  notify:
    - 'Restart the prometheus service'

- name: 'Adapt /etc/default/prometheus for TLS'
  ansible.builtin.lineinfile:
    path: '/etc/default/prometheus'
    line: 'ARGS="--web.config.file /etc/prometheus/webconfig.yml"'
    regex: '^ARGS'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when:
    - 'ansible_distribution == "Debian"'
    - 'enable_tls | bool'
  notify:
    - 'Restart the prometheus service'

- name: 'Create the webconfig for TLS'
  ansible.builtin.template:
    src: 'webconfig.yml.j2'
    dest: '/etc/prometheus/webconfig.yml'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when:
    - 'enable_tls | bool or enable_basic_auth | bool'
  notify:
    - 'Restart the prometheus service'

- name: 'Start and enable the service'
  ansible.builtin.service:
    name: "{{ prometheus_server_service_name }}"
    state: 'started'
    enabled: 'true'
